---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Akoutin.
--- DateTime: 29.03.2022 17:03
---


local composer = require( "composer" )
local scene = composer.newScene()
local widget = require "widget"

local function languageCheck (argument)
    local text = "entity/events/localization/"..gameLanguage
    argument = text..argument
    print(argument)
    return(argument)
end

function scene:create( event )
    local sceneGroup = self.view

    --create background image
    local background = display.newImage( sceneGroup, "creatives/backgrounds/menu-background.png", display.contentWidth, display.contentHeight )
    background.anchorX = 0
    background.anchorY = 0
    background.x, background.y = 0, 0
    background.alpha = 0.5
    sceneGroup:insert( background )


    print (languageCheck("text.txt"))


end

function scene:show( event )
    local sceneGroup = self.view
    local phase = event.phase

    if phase == "will" then
        -- Called when the scene is still off screen and is about to move on screen
    elseif phase == "did" then

    end
end

function scene:hide( event )
    local sceneGroup = self.view
    local phase = event.phase

    if event.phase == "will" then

    elseif phase == "did" then
        -- Called when the scene is now off screen
    end
end

function scene:destroy( event )
    local sceneGroup = self.view

end

---------------------------------------------------------------------------------

-- Listener setup
scene:addEventListener( "create", scene )
scene:addEventListener( "show", scene )
scene:addEventListener( "hide", scene )
scene:addEventListener( "destroy", scene )

-----------------------------------------------------------------------------------------

return scene
