---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Akoutin.
--- DateTime: 31.03.2022 17:19
---

local widget = require "widget"
local composer = require "composer"
local json = require( "json" )

-- global event's text applying
event0000 = "It's okay!"
event0001 = "It's not okay!"
